default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: report_development

test:
  <<: *default
  database: report_test

production:
  <<: *default
  database: report_production
